### ISSUE TITLE
Operator not applying updates to Secrets

### ISSUE THREAD

**Issue by damankaur999** [1Password/onepassword-operator#125] opened 2022-09-15 05:34 UTC
### Your environment

Operator Version: 1.5.0

Connect Server Version: 1.5.6

Kubernetes Version: v1.20

## What happened?
Deployed the operator and connect server using the helm chart. Created a OnePasswordItem and it managed to create the secret. When the password is updated in 1Password, operator doesn't seem to reflect the changes in 1Password. It works initially and then it stops working. Deleting the operator pod resolves the issue intermittently. I've tried to reduce the polling interval but it still doesn't update the secret.

## What did you expect to happen?
Changes to be reflected in the secret

## Steps to reproduce
1. Create a secret in 1Password.
2. Create OnePasswordItem in kubernetes cluster
3. Ensure the secret is created in kubernetes
4. Update the value for the password in 1Password

## Notes & Logs
{
  "level": "error",
  "logger": "controller-runtime.controller",
  "msg": "Reconciler error",
  "controller": "onepassworditem-controller",
  "request": "1password/xxxx",
  "error": "cannot update status: Operation cannot be fulfilled on onepassworditems.onepassword.com \"xxxx\": the object has been modified; please apply your changes to the latest version and try again",

This appeared in the logs once. For subsequent changes, the error doesn't come up and no changes are picked up.

**Comment by Wopple** [comment] 2022-09-16 17:17
I'm experiencing this error frequently now too. In my case it creates the secret in kubernetes but with no data. Sometimes it seems to randomly work, but rarely. I haven't been able to find any error messages though. I've triple and quadruple checked that I've typed everything correctly. I've tried variations of using the title vs UUIDs etc. It seems pretty broken all of a sudden. There was nothing changes with respect to vaults or their permissions. I verified my integration access token still has read/write access to the vault in question.

**Comment by damankaur999** [comment] 2022-09-21 00:11
yeah, I tried deleting the pod but it only seems to work for the 1-2 updated and then it stops working again with no errors or logs.

**Comment by edif2008** [comment] 2022-09-29 10:06
Hey there.

Thank you for raising this odd behaviour. I can see it being frustrating when things no longer work as expected.
I've tried to reproduce this myself, but unfortunately I couldn't make it.

Here's what I did to try to reproduce it:
- Make a clean local cluster (e.g. with minikube)
- Deployed the operator and Connect using helm chart (operator version `v1.5.0` and connect version `v1.5.6`)
- Created a secret with a `OnePasswordItem` resource
- Update fields in the 1Password item using 1Password Desktop App

The types of updates that I've tried:
- Change a field a couple of times
- Change a Password type field 
- Add a new field
- Delete a new field

All of these successfully updated the Kubernetes secret created by the `OnePasswordItem` resource. I've also checked the secret's data and the new values were reflected.

Here are a couple of things that may help a bit in debugging and seeing what's wrong:
- Check the operator's logs and see if there's any update performed by the operator. Here's a sample of logs that should highlight that the Kubernetes secret has been updated:
  ```
  {"level":"info","ts":1664445568.4748816,"logger":"update_op_kubernetes_secrets_task","msg":"Updating kubernetes secret 'secret-name'"}
  {"level":"info","ts":1664445568.4749131,"logger":"update_op_kubernetes_secrets_task","msg":"New secret path: vaults/<vault-uuid>/items/<item-uuid> and version: <new-version-number>"}
  ``` 

- Check the status of the `OnePasswordItem` resource created. They can find it by running the following command:
  ```
  kubectl describe OnePasswordItem <resource-name>
  ```
  Here's an example of the status:
  ```
  Status:
    Conditions:
      Last Transition Time:  2022-09-28T13:26:39Z
      Status:                True
      Type:                  Ready
  ```

- Check the Kubernetes secret's annotations and see if the proper annotations are set. Here's an example of the right annotations:
  ```
  Annotations:  operator.1password.io/item-path: vaults/<vault-uuid>/items/<item-uuid>
                operator.1password.io/item-version: 27
  ```
  The item path should match the one you provided and should point to the desired Item.
  The item version should match with the Item's version. To check that, you can use the 1Password CLI and run `op item get <item-title>`. In the output you will see the Item's version.

- Make sure that the Kubernetes secret is not updated by another resource. The logs provided in the issue's description usually show up when the Kubernetes secret was updated differently than with the `OnePasswordItem` resource and then the operator tries to update the secret.

Let me know if this helps a bit in finding what goes wrong in updating the Kubernetes secret with the `OnePasswordItem` resource.
In the meantime, we will try to investigate further and see if we find anything that can help us reproduce this bug and identify the cause of it.

**Comment by edif2008** [comment] 2023-03-13 16:45
Hey @damankaur999 and @Wopple,

Is this issue still present in your infrastructure?

**Comment by Wopple** [comment] 2023-03-15 02:30
I have not seen it happen again. I can't really provide reproduction steps because I didn't make any changes of note when it happened. I'm guessing there was some hidden lower level error that the operator had a hard time recovering from.

**Comment by edif2008** [comment] 2023-03-20 11:24
Thank you for the insight @Wopple.

I will close this issue for now. Feel free to re-open if this happens again.

**Closed by edif2008** 2023-03-20 11:24 UTC
Labels: bug

**Comment by waddles** [comment] 2023-05-04 07:03
@edif2008 I am also seeing this, it looks like a concurrency issue at the time the OnePassswordItem is first seen after being created by helm. We are using helm2 but I don't expect that will matter.

These are nanosecond precision timestamps from our logging system (formatted as `ns msg | error`)
```
1683178466.7180982 Reconciling OnePasswordItem |
1683178466.8133085 Creating Secret graphql-public-datasources at namespace 'default' |
1683178466.9014702 Reconciling OnePasswordItem |
1683178466.9200048 Secret with name graphql-public-datasources and version 4 already exists |
1683178467.031382 Reconciler error | cannot update status: Operation cannot be fulfilled on onepassworditems.onepassword.com "graphql-public-datasources": the object has been modified; please apply your changes to the latest version and try again
1683178467.0315104 Reconciling OnePasswordItem |
1683178467.04997 Secret with name graphql-public-datasources and version 4 already exists |
1683178467.0603156 Reconciling OnePasswordItem |
1683178467.1491425 Secret with name graphql-public-datasources and version 4 already exists |
```

Confirmed we have only 1 `onepassword-connect-operator` pod running and our monitoring did not detect any change in go_routines or go_threads at that time.

**Comment by waddles** [comment] 2023-05-04 07:36
Restarting the `onepassword-connect` pod has got the `onepassword-operator` pod updating the Secret again.
