### ISSUE TITLE
OnePassword operator unable to find secret Document in vault

### ISSUE THREAD

**Issue by jamesloosli** [1Password/onepassword-operator#107] opened 2022-04-14 16:50 UTC
### Your environment

Operator Version: 1.4.1

Connect Server Version: 1.5.1

Kubernetes Version: v1.21.5-eks-bc4871b

## What happened?
The onepassword operator is unable to find Document type secrets by name.

## What did you expect to happen?
The onepassword operator reconciles a OnePasswordItem referencing a document in a vault into a kubernetes secret.

## Steps to reproduce
Create a `Document` in a onepassword vault, then create a corresponding OnePasswordItem referencing that secret document.

## Notes & Logs
{"level":"info","ts":1649954919.1657534,"logger":"controller_onepassworditem","msg":"Reconciling OnePasswordItem","Request.Namespace":"default","Request.Name":"idrsa"}
{"level":"error","ts":1649954919.1738467,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"onepassworditem-controller","request":"default/idrsa","error":"Failed to retrieve item: No items found with identifier
\"idrsa\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/workspace/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/workspace/vendor/sigs.k8
s.io/controller-runtime/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controll
er.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/w
orkspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/workspace/ve
ndor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}

**Comment by jamesloosli** [comment] 2022-04-14 16:51
Our setup is working with Secure Notes, but no luck with Documents.

**Comment by edif2008** [comment] 2022-06-08 18:50
Hi there,

We are having trouble reproducing your issue. From the looks of the logs you have shared it looks like the operator is unable to find the 1Password item, I would expect a different error log if there was a problem converting the 1Password item to a kubernetes Secret. 

Can you try doing the following steps:
- Create an item of category `Document` 
- Attach the file that you want to use in your Kubernetes environment
- Add a title to the `Document` item. Make sure that the title doesn't have any spaces it it. you can use `-` instead.
- Create a OnePasswordItem secret that will fetch the created item

Let me know if after following these steps, you can access your secret in Kubernetes.

**Comment by Subsack** [comment] 2022-08-15 14:27
@edif2008 We're having similar issues with items of category `Document`, everything else works fine. I created it according to your steps above but when we create a OnePasswordItem that references an item with a Document, no secret is created.

connect-api is responding 200 to the operator:
`{"log_message":"(I) GET /v1/vaults/zpblhx5ygojkpdc22mdiedv2ea/items/ygfpwyut2k2arw3ixdsypijbs4 completed (200: OK)"`

the connect operator is complaing about not being able to update the status as seen in issue [122](https://github.com/1Password/onepassword-operator/issues/122) as well:
`{"level":"error","ts":1660573252.8795276,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"onepassworditem-controller","request":"dev/secret","error":"cannot update status: onepassworditems.onepassword.com \"secret\" not found"`

In our case no secret is created, if we switch to a non-document secret there are no issues.

**Comment by edif2008** [comment] 2022-08-15 15:23
Could you try this with Connect 1.5.6? 
Version 1.5.4 had some issues with document files, which led to not being able to get the file's content.

**Comment by Subsack** [comment] 2022-08-16 06:10
> Could you try this with Connect 1.5.6? Version 1.5.4 had some issues with document files, which led to not being able to get the file's content.

Yeah that worked - thank you! We're still experiencing [122](https://github.com/1Password/onepassword-operator/issues/122) but everything still seems to work so it's just annoying, not breaking :)

**Comment by edif2008** [comment] 2022-08-16 16:00
Glad to hear that it worked. I will close this issue.

As for the other one, I will raise it with my team and come back to you once we've managed to reproduce the bug.

**Closed by edif2008** 2022-08-16 16:00 UTC
Labels: bug, tracked
