### ISSUE TITLE
Secrets of same type not containing data

### ISSUE THREAD

**Issue by freekdegreef** [1Password/onepassword-operator#70] opened 2021-09-16 08:23 UTC
Operator Version: 1.0.1
Connect Server Version: 1.2.0
Kubernetes Version: 1.20.9

## What happened?
When creating OnePasswordItem's secrets get created for every one of them but some of them don't contain any data. This happens for 1P Login item's so that are of the same type. In some of these some data is missing as well so for example `username` and `password` are present but a `url` field isn't.

## Steps to reproduce
1. Create OnePasswordItem yaml file
`apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: secret
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/vault-name/items/secret"`
  
  2. Apply that file
  `kubectl apply -f secret.yaml`
  
  3. Get the secret content as json
  `kubectl get secret secret -o=json`
  
  4. Output
  `{
    "apiVersion": "v1",
    "kind": "Secret",
    "metadata": {
        "annotations": {
            "operator.1password.io/auto-restart": "true",
            "operator.1password.io/item-path": "vaults/xxxxxxxxx/items/xxxxxxxxx",
            "operator.1password.io/item-version": "4"
        },
        "creationTimestamp": "2021-09-15T14:31:21Z",
        "name": "secret",
        "namespace": "default",
        "resourceVersion": "32428061",
        "uid": "f9sad2e-f080-4fa7-b44e-db0aisjd819e80"
    },
    "type": "Opaque"
}`

**Comment by florisvdg** [comment] 2021-09-17 09:11
Could you give some examples of fields that you expected to be there but were not? Only `url` on a login item or are there more?

**Comment by freekdegreef** [comment] 2021-09-21 06:59
Sure. So I have an entry called `redis` containing a `password` and an `url` field called that doesn't populate at all. Same for another entry that has an `url` field so possibly the url data might be at the root of this issue.

I also have an entry called `pusher-app` with custom fields called `password` `pusher-app-id` and `pusher-app-key` that did get populated.

**Comment by verkaufer** [comment] 2021-09-27 20:09
Hey @freekdegreef - am I understanding correctly that the problem seems isolated to the `url` field? 

I'm thinking this could be one of two things:
1. We're talking about different ideas of the `url` field: there's a `urls` key on item objects that's an array of URLs _and_ you there are item fields that can have the type `URL`.  (This distinction determines how 1Password apps display URLs)

2. There's a bug with the URL field type that we're not doing a good job handling. 

Could you confirm for me:
1. The item you're trying to import has a **field** with the name `url` and you're not trying to use the `urls` item key
2. Your `url` field is just a string.

You could quickly confirm both of these by making a request to your Connect instance: `GET /v1/vaults/:vault_id/items/:item_id`

**Comment by freekdegreef** [comment] 2021-09-29 08:16
It looks like it. This is the output I got when I made that request.

`{"id":"example-id","title":"mysql","urls":[{"primary":true,"href":"example.com"}],"version":5,"vault":{"id":"example-id"},"category":"PASSWORD","sections":[{"id":"linked items","label":"Related Items"}],"fields":[{"id":"password","type":"CONCEALED","purpose":"PASSWORD","label":"password"},{"id":"notesPlain","type":"STRING","purpose":"NOTES","label":"notesPlain"}],"lastEditedBy":"id-here","createdAt":"2021-09-15T13:55:07Z","updatedAt":"2021-09-15T14:20:23Z"}/app # `

So it looks like that `urls` array is there. The first entry I have there is called `url` instead of the default which is `website` I think.

**Comment by verkaufer** [comment] 2021-09-30 01:05
Thanks for providing that output 👍  

To make sure we're on the same page:
You created a `Password` item and set a website value. When you tried loading that item into Kubernetes as a secret, you expected it to pull in the URL of the website you set. Does that sound right?

If so, I think the issue is we don't map the `item.urls[]` array to secret data keys in the Kubernetes secret. I'll let my colleagues know about this and we'll get back to you. 

In the mean time, you could work around the issue by creating a new field to store the URL instead of storing it in the `urls` or `website` field. If it's an item field it will be included in the Kubernetes secret.

**Comment by freekdegreef** [comment] 2021-09-30 12:22
Thanks I will give that a try after the weekend. The only strange thing is that when you look at my original output in the first post that all the contents of the secret are missing. Would that be resolved by this as well you think?

**Comment by jillianwilson** [comment] 2022-06-08 17:52
Hi there!

Just wanted to check in and ask if this is still an issue you are running into? We are unable to replicate this issue on our latest releases (we've had a few releases since your last comment), but would love to resolve the problem if it's still causing you trouble.

Cheers

**Comment by edif2008** [comment] 2023-03-13 16:35
Closing since the issue cannot be reproduced with the latest version of the operator (the issue may already be solved).
Feel free to re-open if the issue is still present.

**Closed by edif2008** 2023-03-13 16:35 UTC
Labels: bug, tracked
