### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by robb-j** [1Password/onepassword-operator#149] opened 2023-01-14 20:17 UTC
### Your environment

Operator Version: 1.5.7

Connect Server Version: 1.5.7?

Kubernetes Version: v1.23.14

## What happened?

The memory usage of my `onepassword-connect` pod was 1097Mi which seems very high, is there a normal amount of memory this container should stay around?

## What did you expect to happen?

I thought the container would need a lot less memory 

## Steps to reproduce

1. The container had been running for 38 days, after restarting the container it was using around 30Mi of memory.
   This is on a really small cluster with only 8 OnePasswordItem resources in it.
2. The memory seems to go up a few `Mi` every few minute

## Notes & Logs

**before restarting**
<img width="682" alt="before" src="https://user-images.githubusercontent.com/1526174/212494481-355d21c2-8fbc-4449-9f78-6079d8203678.png">

**after restarting**
<img width="607" alt="after" src="https://user-images.githubusercontent.com/1526174/212494484-aa71f878-3667-4dad-9227-08ae78b3c950.png">

my `values.yml` passed to helm:

```yml
operator:
  create: true
  watchNamespace: [r0b-system,games,default,tools,hyem-tech]
```

**Comment by mhixon4479** [comment] 2023-01-25 17:09
Seeing similar here. The pod itself isn't being actively used although memory seems to leak until it's OOM killed.

<img width="945" alt="Screen Shot 2023-01-25 at 9 07 20 AM" src="https://user-images.githubusercontent.com/101131697/214631881-6aa569d3-5b7d-4868-88e1-0e6c3dad079f.png">

**Comment by katherine-black** [comment] 2023-02-16 21:36
Its a shame there are not default values included for the resources requests/limits in the helm chart.

**Comment by gladiatr72** [comment] 2024-01-04 16:08
hrm.  has this been resolved with newer versions?  I set up a goldilocks monitor for it yesterday and am getting this as a resources recommendation:

```
resources:
  requests:
    cpu: 163m
    memory: 2282M
  limits:
    cpu: 163m
    memory: 2282M
```

**Comment by JaniszM** [comment] 2024-02-08 10:47
+1, same here. My pod reaches 1GB in two days.

**Comment by gladiatr72** [comment] 2024-02-22 16:04
Bueller...

Bueller...

(sigh)

Dear 1password: 

Hello.  You might remember me from January 4th of this year.  (I think I tripped over @robb-j's corpse in the parking lot, but, no matter, I'm here now). This isn't an open-source project in so much as anyone using it is a paying customer or works for a paying customer.  If this operator should be considered _abandoned_, please have the courtesy of letting us know so we can make other arrangements.

Thanks

**Comment by mhixon4479** [comment] 2024-02-22 17:41
Second the motion.

**Comment by samirahafezi** [comment] 2024-02-26 19:54
Hey @gladiatr72!

Samira here from 1Password 👋🏻  Thanks for bringing this to our attention. We do keep a close eye on all of our repos and this issue in particular hasn't been forgotten. Memory issues tend to be tricky and we've been working on our end to try to figure this one out. Apologies on not keeping the issue updated, but it has not been forgotten. 

To alleviate your concerns about this repo being abandoned, I want to stress that this is not the case. We are actively working on it and in fact, we released a new version last month that addressed a few bugs. [Here are the release notes](https://github.com/1Password/onepassword-operator/releases/tag/v1.8.1) on that particular release.

We'll continue making updates to this repo over time and will keep the issue updated with our progress on this memory issue. 

Thanks!

**Comment by gladiatr72** [comment] 2024-04-03 16:18
I'm starting to feel a bit neglected again...

**Comment by gladiatr72** [comment] 2024-08-20 22:15
@edif2008 what's the word?

**Comment by AndyTitu** [comment] 2024-08-29 09:48
Hey @gladiatr72, are you familiar with [this GitHub issue](https://github.com/1Password/connect/issues/23)? There have been a few developments there:
- a couple of memory leaks were identified and addressed in the latest versions of the connect-sync and connect-api images >1.7.0.
- another cause for Kubernetes reporting a high memory usage for Connect was related to a particularity of the `container_memory_usage_bytes` metric that includes memory that is used for "caching" and can be reclaimed by the OS. The assumption is that `container_memory_working_set_bytes` is harmless as long as `container_memory_rss` does not increase as well. Applying a memory limit for Connect in k8s [seems](https://github.com/1Password/connect/issues/23#issuecomment-1658756442) forces the OS to clear and reclaim the memory used for caching which seems to bound the memory consumption. To quickly validate this hypothesis it is possible to use `sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"` on the k8s host.

Let me know if any of the above is helpful in your case!

**Comment by AndyTitu** [comment] 2024-09-27 10:46
### Summary

Multiple users reported abnormal memory consumption growth reported by Kubernetes for the `onepassword-connect` pod. The pod would eventually get OOM killed by Kubernetes, due to the high memory consumption.

### How to Reproduce

1. Start a minikube local cluster

```bash
brew install minikube
minikube start
```

1. Create connect credentials
2. Deploy connect to a Kubernetes environment

```bash
## using Helm to deploy the Kubernetes operator with the production version of connect
helm repo add 1password https://1password.github.io/connect-helm-charts
helm install connect 1password/connect --set-file connect.credentials=1password-credentials.json --set operator.create=true --set operator.token.value = <your connect token>

## deploying local versions of Connect from the op repo

eval $(minikube docker-env)
## Modify the makefile to tag the docker images with some new names
make connect/docker
## Modify the deployment/deploy.yaml to specify the new docker image names and add imagePullPolicy: Never to make sure the images aren't pulled from somewhere else
make connect/k8s
```

1. Track memory usage consumption metrics

```bash
minikube addons enable metrics-server

kubectl top pod --containers 

POD                                            NAME                  CPU(cores)   MEMORY(bytes)   
onepassword-connect-67b475c6d9-bxd2k           connect-api           3m           20Mi           
onepassword-connect-67b475c6d9-bxd2k           connect-sync          3m           9Mi             
onepassword-connect-operator-b4d8fcc7c-9mtg7   onepassword-connect   3m           34Mi  
```

1. Spam the connect-api container and watch the memory consumption increase

```bash
kubectl port-forward service/onepassword-connect 8080:8080
repeat 100000000000 curl -H "Authorization: Bearer $OP_CONNECT_TOKEN"  "http://localhost:8080/v1/vaults/xw33qlvug6moegr3wkk5zkenoa/items/45aeh7xabv2ctvphuzrcr72ovq" > /dev/null

## After 1 hour
kubectl top pod --containers 
POD                                            NAME                  CPU(cores)   MEMORY(bytes)   
onepassword-connect-67b475c6d9-bxd2k           connect-api           3m           131Mi           
onepassword-connect-67b475c6d9-bxd2k           connect-sync          3m           9Mi             
onepassword-connect-operator-b4d8fcc7c-9mtg7   onepassword-connect   3m           34Mi  
```

## Experiments and findings

### Hypothesis

These were the hypothesis we were looking to validate or dismiss as the cause of Kubernetes reporting high memory usage and eventually killing the connect pod with a OOM message:

- Memory leak in the connect-sync Go program.
- Memory leak in connect-api Go program.
- The memory consumption is specific to the docker image we are using
- Unexpected memory usage caused by the sqlite database
- Memory is not managed (tracked and/or released) by Kubernetes as we initially expected

### REJECTED: Memory leak in the connect-sync Go program

- It was clear from the memory usage metrics reported by Kubernetes that the connect-sync container’s memory usage was unchanged and that the problem was in the connect-api image.

```bash
kubectl top pod --containers 
POD                                            NAME                  CPU(cores)   MEMORY(bytes)   
onepassword-connect-67b475c6d9-bxd2k           connect-api           3m           131Mi           
onepassword-connect-67b475c6d9-bxd2k           connect-sync          3m           9Mi             
onepassword-connect-operator-b4d8fcc7c-9mtg7   onepassword-connect   3m           34Mi  
```

Hypothesis **rejected**.

### REJECTED: The memory consumption is specific to the docker image we are using

- Used various base images for building and deploying connect, so we excluded that the op-distroless image from our registry is the culprit. We also used `ubuntu:latest` and `debian:latest` which resulted in the same behaviour.

Hypothesis **rejected.**

### REJECTED: Memory leak in connect-api Go program

- Monitored the heap usage of the Go application using `pprof` . We deployed a profiled connect server to the minkube cluster, and port forwarded the profile live metrics. When comparing the heap profile at different moments in time we found that no leakage was present.
- Additionally, the memory used by the connect-api server was inspected by entering the container directly and using linux commands such as `top` or `cat /proc/1/smaps | grep -i pss |  awk '{Total+=$2} END {print Total/1024" MB"}’` . At most 31MB of memory was in the process’ use at all times throughout the experiments.

Hypothesis **rejected**.

### CONFIRMED: Memory is not managed (tracked and/or released) by Kubernetes as we initially expected

- [[It is known](https://kubernetes.io/docs/concepts/architecture/cgroups/)](https://kubernetes.io/docs/concepts/architecture/cgroups/) that Kubernetes-reported metrics (reported by cAdvisor) are consistent with the ones present in `/sys/fs/cgroup/memory.stat` reported by the kernel cgroups. After inspecting this file it was clear that most of the memory consumption was associated to the `inactive_file` and `active_file` which together make for the total `file` metrics, which [[are documented](https://docs.kernel.org/admin-guide/cgroup-v2.html)](https://docs.kernel.org/admin-guide/cgroup-v2.html) as tracking the “amount of memory used to cache filesystem data, including tmpfs and shared memory”.

```bash
opuser@onepassword-connect-67b475c6d9-bxd2k:/$ cat /sys/fs/cgroup/memory.stat
anon 14594048
**file** **119603200        # 119 MB**
kernel_stack 212992
pagetables 368640
percpu 0
sock 0
shmem 0
file_mapped 5873664
file_dirty 0
file_writeback 0
swapcached 0
anon_thp 0
file_thp 0
shmem_thp 0
inactive_anon 14565376
active_anon 16384
**inactive_file** **7577600  # 7MB**
**active_file** **112025600  # 112 MB**
unevictable 0
slab_reclaimable 3628128
slab_unreclaimable 173880
slab 3802008
workingset_refault_anon 0
workingset_refault_file 1655
workingset_activate_anon 0
workingset_activate_file 429
workingset_restore_anon 0
workingset_restore_file 410
workingset_nodereclaim 0
pgfault 1035843
pgmajfault 126
pgrefill 0
pgscan 0
pgsteal 0
pgactivate 26949
pgdeactivate 0
pglazyfree 0
pglazyfreed 0
thp_fault_alloc 0
thp_collapse_alloc 0

AND

~ kubectl top pod --containers                                                 
POD                                            NAME                  CPU(cores)   MEMORY(bytes)   
onepassword-connect-67b475c6d9-bxd2k           connect-api           3m           **131Mi**           
onepassword-connect-67b475c6d9-bxd2k           connect-sync          2m           9Mi             
onepassword-connect-operator-b4d8fcc7c-9mtg7   onepassword-connect   3m           34Mi 

AND

cat /proc/1/smaps | grep -i pss |  awk '{Total+=$2} END {print Total/1024" MB"}'
28.8066 MB

### The total reported memory of 131 MB can be obtained by adding up the memory taken up by the Go process. (~29MB) and the active file-backed memory (~112)
```

This type of cache memory is also counted by Kubernetes in the total memory usage it reports and historically caused killing of pods:

- https://github.com/kubernetes/kubernetes/issues/114142
- https://github.com/kubernetes/kubernetes/issues/43916
- https://bugzilla.kernel.org/show_bug.cgi?id=207273

Hypothesis **confirmed.**

### CONFIRMED: Unexpected memory usage caused by the sqlite database

Given the above findings about file-backed memory being the underlying cause of why Kubernetes reports such high memory usage consumption, and since that cache role is to optimize I/O operations, I was inclined to check the sole known source of I/O operations of connect-api: the sqlite  database. 

```bash
opuser@onepassword-connect-67b475c6d9-bxd2k:/$ ls -lh /home/opuser/.op/data/
total 107M
**-rw-r--r-- 1 opuser 999 103M Sep 19 20:43 1password.sqlite**
-rw-r--r-- 1 opuser 999  32K Sep 19 20:43 1password.sqlite-shm
-rw-r--r-- 1 opuser 999 4.0M Sep 19 20:43 1password.sqlite-wal
drwx------ 2 opuser 999 4.0K Sep 18 12:25 files
```

It was found that the database keeps growing in time as more and more operations are performed, even though those operations only retrieve the same item over and over again. This is due to the **activity_events** table which we keep adding entries to.

First image where we have 303k entries:

![Screenshot 2024-09-20 at 13.53.01.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/4664d4fe-9660-4b45-a7ae-9a060d9cc686/b38dacd0-9777-4bd7-8292-854646ade6c0/Screenshot_2024-09-20_at_13.53.01.png)

Second image, after less than 1 minute of spamming with 308k entries:

![Screenshot 2024-09-20 at 13.53.20.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/4664d4fe-9660-4b45-a7ae-9a060d9cc686/45d45f1a-7e92-4a4e-b78b-432575ec777c/Screenshot_2024-09-20_at_13.53.20.png)

The difference of 5k entries account for 3MB of size in the `1password.sqlite` file. After ~ 2 days of running the connect-api container, the database has never decreased in size. 

Even though it is unclear whether the DB growth solely accounts for the FS cache growth, it definitely accounts for some of it and is something we should address.

### Diagnostic

Kubernetes also tracks filesystem cache as part of the total memory usage of a Pod. Filesystem cache is used to optimize I/O operations but is not absolutely necessary for a program to run and the OS can evict those if needed. The filesystem cache can grow in order to optimize I/O operations further or in case the disk itself grows in size. 

When using resource limits in the Kubernetes deployment file, the filesystem cache growth was capped and the container never actually crossed that memory boundary:

![Screenshot 2024-09-20 at 14.11.47.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/4664d4fe-9660-4b45-a7ae-9a060d9cc686/de7769c4-06a7-4bcc-996e-0689fce83e70/Screenshot_2024-09-20_at_14.11.47.png)

### Solution

**Short term**: limit resource consumption in our containers: document the recommended limits as being 128 MiB of memory usage and 0.2 CPU usage (by experimentation it was seen that the memory usage never crossed 31 MB but the 128Mib threshold is already present in the connect `deployment.yaml` file in the open source operator repo and we were also using this number in the op repo which should give enough space for decrypting wildly large items and files), enforce these limits in the helm charts.

**Long term:** cap the database’s constant growth by deleting old activity events.### Summary

Multiple users reported abnormal memory consumption growth reported by Kubernetes for the `onepassword-connect` pod. The pod would eventually get OOM killed by Kubernetes, due to the high memory consumption.

### How to Reproduce

1. Start a minikube local cluster

```bash
brew install minikube
minikube start
```

2. Create connect credentials
3. Deploy connect to a Kubernetes environment

```bash
## using Helm to deploy the Kubernetes operator with the production version of connect
helm repo add 1password https://1password.github.io/connect-helm-charts
helm install connect 1password/connect --set-file connect.credentials=1password-credentials.json --set operator.create=true --set operator.token.value = <your connect token>

## deploying local versions of Connect from the op repo

eval $(minikube docker-env)
## Modify the makefile to tag the docker images with some new names
make connect/docker
## Modify the deployment/deploy.yaml to specify the new docker image names and add imagePullPolicy: Never to make sure the images aren't pulled from somewhere else
make connect/k8s
```

4. Track memory usage consumption metrics

```bash
minikube addons enable metrics-server

kubectl top pod --containers 

POD                                            NAME                  CPU(cores)   MEMORY(bytes)   
onepassword-connect-67b475c6d9-bxd2k           connect-api           3m           20Mi           
onepassword-connect-67b475c6d9-bxd2k           connect-sync          3m           9Mi             
onepassword-connect-operator-b4d8fcc7c-9mtg7   onepassword-connect   3m           34Mi  
```

5. Spam the connect-api container and watch the memory consumption increase

```bash
kubectl port-forward service/onepassword-connect 8080:8080
repeat 100000000000 curl -H "Authorization: Bearer $OP_CONNECT_TOKEN"  "http://localhost:8080/v1/vaults/xw33qlvug6moegr3wkk5zkenoa/items/45aeh7xabv2ctvphuzrcr72ovq" > /dev/null

## After 1 hour
kubectl top pod --containers 
POD                                            NAME                  CPU(cores)   MEMORY(bytes)   
onepassword-connect-67b475c6d9-bxd2k           connect-api           3m           131Mi           
onepassword-connect-67b475c6d9-bxd2k           connect-sync          3m           9Mi             
onepassword-connect-operator-b4d8fcc7c-9mtg7   onepassword-connect   3m           34Mi  
```

## Experiments and findings

### Hypothesis

These were the hypothesis we were looking to validate or dismiss as the cause of Kubernetes reporting high memory usage and eventually killing the connect pod with a OOM message:

- Memory leak in the connect-sync Go program.
- Memory leak in connect-api Go program.
- The memory consumption is specific to the docker image we are using
- Unexpected memory usage caused by the sqlite database
- Memory is not managed (tracked and/or released) by Kubernetes as we initially expected

### REJECTED: Memory leak in the connect-sync Go program

- It was clear from the memory usage metrics reported by Kubernetes that the connect-sync container’s memory usage was unchanged and that the problem was in the connect-api image.

```bash
kubectl top pod --containers 
POD                                            NAME                  CPU(cores)   MEMORY(bytes)   
onepassword-connect-67b475c6d9-bxd2k           connect-api           3m           131Mi           
onepassword-connect-67b475c6d9-bxd2k           connect-sync          3m           9Mi             
onepassword-connect-operator-b4d8fcc7c-9mtg7   onepassword-connect   3m           34Mi  
```

Hypothesis **rejected**.

### REJECTED: The memory consumption is specific to the docker image we are using

- Used various base images for building and deploying connect, so we excluded that the op-distroless image from our registry is the culprit. We also used `ubuntu:latest` and `debian:latest` which resulted in the same behaviour.

Hypothesis **rejected.**

### REJECTED: Memory leak in connect-api Go program

- Monitored the heap usage of the Go application using `pprof` . We deployed a profiled connect server to the minkube cluster, and port forwarded the profile live metrics. When comparing the heap profile at different moments in time we found that no leakage was present.
- Additionally, the memory used by the connect-api server was inspected by entering the container directly and using linux commands such as `top` or `cat /proc/1/smaps | grep -i pss |  awk '{Total+=$2} END {print Total/1024" MB"}’` . At most 31MB of memory was in the process’ use at all times throughout the experiments.

Hypothesis **rejected**.

### CONFIRMED: Memory is not managed (tracked and/or released) by Kubernetes as we initially expected

- [[It is known](https://kubernetes.io/docs/concepts/architecture/cgroups/)](https://kubernetes.io/docs/concepts/architecture/cgroups/) that Kubernetes-reported metrics (reported by cAdvisor) are consistent with the ones present in `/sys/fs/cgroup/memory.stat` reported by the kernel cgroups. After inspecting this file it was clear that most of the memory consumption was associated to the `inactive_file` and `active_file` which together make for the total `file` metrics, which [[are documented](https://docs.kernel.org/admin-guide/cgroup-v2.html)](https://docs.kernel.org/admin-guide/cgroup-v2.html) as tracking the “amount of memory used to cache filesystem data, including tmpfs and shared memory”.

```bash
opuser@onepassword-connect-67b475c6d9-bxd2k:/$ cat /sys/fs/cgroup/memory.stat
anon 14594048
**file 119603200        # 119 MB**
kernel_stack 212992
pagetables 368640
percpu 0
sock 0
shmem 0
file_mapped 5873664
file_dirty 0
file_writeback 0
swapcached 0
anon_thp 0
file_thp 0
shmem_thp 0
inactive_anon 14565376
active_anon 16384
**inactive_file 7577600  # 7MB**
**active_file 112025600  # 112 MB**
unevictable 0
slab_reclaimable 3628128
slab_unreclaimable 173880
slab 3802008
workingset_refault_anon 0
workingset_refault_file 1655
workingset_activate_anon 0
workingset_activate_file 429
workingset_restore_anon 0
workingset_restore_file 410
workingset_nodereclaim 0
pgfault 1035843
pgmajfault 126
pgrefill 0
pgscan 0
pgsteal 0
pgactivate 26949
pgdeactivate 0
pglazyfree 0
pglazyfreed 0
thp_fault_alloc 0
thp_collapse_alloc 0

AND

~ kubectl top pod --containers                                                 
POD                                            NAME                  CPU(cores)   MEMORY(bytes)   
onepassword-connect-67b475c6d9-bxd2k           connect-api           3m           **131Mi**           
onepassword-connect-67b475c6d9-bxd2k           connect-sync          2m           9Mi             
onepassword-connect-operator-b4d8fcc7c-9mtg7   onepassword-connect   3m           34Mi 

AND

cat /proc/1/smaps | grep -i pss |  awk '{Total+=$2} END {print Total/1024" MB"}'
28.8066 MB

### The total reported memory of 131 MB can be obtained by adding up the memory taken up by the Go process. (~29MB) and the active file-backed memory (~112)
```

This type of cache memory is also counted by Kubernetes in the total memory usage it reports and historically caused killing of pods:

- https://github.com/kubernetes/kubernetes/issues/114142
- https://github.com/kubernetes/kubernetes/issues/43916
- https://bugzilla.kernel.org/show_bug.cgi?id=207273

Hypothesis **confirmed.**

### CONFIRMED: Unexpected memory usage caused by the sqlite database

Given the above findings about file-backed memory being the underlying cause of why Kubernetes reports such high memory usage consumption, and since that cache role is to optimize I/O operations, I was inclined to check the sole known source of I/O operations of connect-api: the sqlite  database. 

```bash
opuser@onepassword-connect-67b475c6d9-bxd2k:/$ ls -lh /home/opuser/.op/data/
total 107M
**-rw-r--r-- 1 opuser 999 103M Sep 19 20:43 1password.sqlite**
-rw-r--r-- 1 opuser 999  32K Sep 19 20:43 1password.sqlite-shm
-rw-r--r-- 1 opuser 999 4.0M Sep 19 20:43 1password.sqlite-wal
drwx------ 2 opuser 999 4.0K Sep 18 12:25 files
```

It was found that the database keeps growing in time as more and more operations are performed, even though those operations only retrieve the same item over and over again. This is due to the **activity_events** table which we keep adding entries to.

After less than a minute of request spamming, we encountered a difference of 5k entries which account for 3MB of size in the `1password.sqlite` file. After ~ 2 days of running the connect-api container, the database has never decreased in size. 

Even though it is unclear whether the DB growth solely accounts for the FS cache growth, it definitely accounts for some of it and is something we should address.

### Diagnostic

Kubernetes also tracks filesystem cache as part of the total memory usage of a Pod. Filesystem cache is used to optimize I/O operations but is not absolutely necessary for a program to run and the OS can evict those if needed. The filesystem cache can grow in order to optimize I/O operations further or in case the disk itself grows in size. 

When using resource limits in the Kubernetes deployment file, the filesystem cache growth was capped and the container never actually crossed that memory boundary.

### Solution

**Short term**: limit resource consumption in our containers: document the recommended limits as being **128 MiB** of memory usage and **0.2 CPU usage** (by experimentation it was seen that the memory usage never crossed 31 MB but the 128Mib threshold should give enough space for decrypting wildly large items and files).

**Long term:** cap the database’s constant growth by deleting old activity events.

**Comment by AndyTitu** [comment] 2024-09-27 11:03
We conducted a research of the reported issues and came with the above conclusions ⬆️. As of now, we have adopted the short term solution and this issue is considered resolved, but feel free to open a new issue if other related problems occur.

**Closed by AndyTitu** 2024-09-27 11:03 UTC
Labels: bug
